# Generated by Django 5.2.5 on 2025-08-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
