# Generated by Django 5.2.5 on 2025-09-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classroom_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='slug',
        ),
    ]
