# Generated by Django 5.2.5 on 2025-09-14 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_file'),
        ('classes', '0006_remove_classroom_slug'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-graded_at']},
        ),
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (90-100)'), ('A', 'A (80-89)'), ('B+', 'B+ (70-79)'), ('B', 'B (60-69)'), ('C+', 'C+ (50-59)'), ('C', 'C (40-49)'), ('D', 'D (30-39)'), ('F', 'F (0-29)')], max_length=2),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('classroom', 'student', 'assignment')},
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_score', models.FloatField(default=0.0)),
                ('performance_trend', models.CharField(default='stable', max_length=20)),
                ('predicted_final_grade', models.CharField(default='C', max_length=2)),
                ('submission_rate', models.FloatField(default=0.0)),
                ('participation_score', models.FloatField(default=0.0)),
                ('at_risk', models.BooleanField(default=False)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'classroom')},
            },
        ),
    ]
