# Generated by Django 5.2.4 on 2025-09-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_options_grade_assignment_grade_grade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnalytics',
        ),
    ]
